name: "Gemini AI Code Review Action"
description: "Get an explanation of code changes in a pull/push requests and comment on it"
inputs:
  github-token:
    description: "GitHub Token"
    required: true
  gemini-api-key:
    description: "Gemini API Key"
    required: true
  model:
    description: "Gemini Model"
    required: false
    default: "gemini-pro"
  email-host:
    description: "Email Host"
    required: false
    default: ""
  email-port:
    description: "Email Port"
    required: false
    default: ""
  email-user:
    description: "Email User"
    required: false
    default: ""
  email-pass:
    description: "Email Pass"
    required: false
    default: ""
  email-from:
    description: "Email From"
    required: false
    default: ""
  email-to:
    description: "Email To"
    required: false
    default: ""
  email-bcc:
    description: "Email BCC"
    required: false
    default: ""
  email-secure:
    description: "Email Secure"
    required: false
    default: ""
runs:
  using: "node20"
  main: "src/index.js"
branding:
  icon: 'code'
  color: 'green'