name: "Gemini AI Code Review Action"
description: "Get an explanation of code changes in a pull/push requests and comment on it"
inputs:
  github-token:
    description: "GitHub Token"
    required: true
  gemini-api-key:
    description: "Gemini API Key"
    required: true
  model:
    description: "Gemini Model"
    required: false
    default: "gemini-pro"
  model:
    description: "email-host"
    required: false
    default: ""
  model:
    description: "email-port"
    required: false
    default: ""
  model:
    description: "email-user"
    required: false
    default: ""
  model:
    description: "email-pass"
    required: false
    default: ""
  model:
    description: "email-from"
    required: false
    default: ""
  model:
    description: "email-to"
    required: false
    default: ""
  model:
    description: "email-bcc"
    required: false
    default: ""
  model:
    description: "email-secure"
    required: false
    default: ""
runs:
  using: "node20"
  main: "src/index.js"
branding:
  icon: 'code'
  color: 'green'